service: slashmap # NOTE: update this with your service name

custom:
  bucket: slashmap-images

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  tags:
    project: slashmap
    team: innovation
  profile: default # aws config provile to use from ~/.aws/config
  apiName: slashmap
  stackTags: # Optional CF stack tags
    team: innovation
    project: slashmap
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*"   

functions:
  analysis:
    description: get analysis of jpg file in s3 at provided key location in slashmap bucket
    handler: analysis.handler
    events:
      - http:
          path: analysis
          method: get
          cors:
            origin: '*'
            maxAge: 86400
    # Define function environment variables here
    environment:
      S3_BUCKETNAME: ${self:custom.bucket}

# you can add CloudFormation resource templates here
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
